name: Azure Python 3.10
on:
  push:
    branches: ["*"]
  pull_request:
    branches: [feature/*, bugfix/*]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.13
      - name: Install dependencies
        run: make install
      - name: Lint with flake8
        run: make lint
      - name: Test with pytest
        run: make test
